### ISSUE TITLE
Implement a different parser for Headings and relevant content

### ISSUE THREAD

**Issue by ChakshuGautam** [KDwevedi/c4gt-server#3]
The [current implementation](https://github.com/KDwevedi/c4gt-server/blob/2cbe5dcec6d90a0452f6b43c3bdb3fbafb948285/utils/markdown_handler.py#L1) is not handling errors in spelling.

Features
1. Creates a JSON out of the parsed data.
2. Searches for headings in a fuzzy manner. Configurable threshold. Currently set to 80% match.

[See sample implementation in google colab here](https://colab.research.google.com/drive/1has1hydj4rvzZGaAG_bLg3XzNyHCR892?usp=sharing).

**Comment by KDwevedi** [comment]
Using a new fuzzy parser now
